-- Use proper database.
USE `job_beacon_maine`;

-- Drop existing tables if they exist.
DROP TABLE IF EXISTS `SKILL`;
DROP TABLE IF EXISTS `RESOURCE`;
DROP TABLE IF EXISTS `SKILL_RESOURCE`;

-- SKILL table to store various skills. Reasoning for ID is in case for future skill aliasing.
CREATE TABLE `SKILL` (
  `idSKILL` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (`idSKILL`),
  UNIQUE KEY `NAME_UNIQUE` (`NAME`)
);

-- RESOURCE for SKILL educational resources.
CREATE TABLE `RESOURCE` (
  `idRESOURCE` INT NOT NULL AUTO_INCREMENT,
  `URL` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idRESOURCE`)
);

-- SKILL RESOURCE many to many table. 
CREATE TABLE `SKILL_RESOURCE` (
  `idRESOURCE` INT NOT NULL,
  `idSKILL` INT NOT NULL,
  PRIMARY KEY (`idRESOURCE`, `idSKILL`),
  CONSTRAINT `fk_skill_resource_skill`
    FOREIGN KEY (`idSKILL`)
    REFERENCES `SKILL` (`idSKILL`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sill_resource_resource`
    FOREIGN KEY (`idRESOURCE`)
    REFERENCES `RESOURCE` (`idRESOURCE`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

-- REQUIRES SKILL many to many table between JOB and SKILL.
CREATE TABLE `REQUIRES_SKILL` (
  `idJOB` INT NOT NULL,
  `idSKILL` INT NOT NULL,
  PRIMARY KEY (`idJOB`, `idSKILL`),
  CONSTRAINT `fk_requires_skill_job`
    FOREIGN KEY (`idJOB`)
    REFERENCES `JOB` (`idJOB`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_requires_skill_skill`
    FOREIGN KEY (`idSKILL`)
    REFERENCES `SKILL` (`idSKILL`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

-- HAS SKILL many to many table between STUDENT_ALUM and SKILL.
CREATE TABLE `HAS_SKILL` (
  `idUSER` INT NOT NULL,
  `idSKILL` INT NOT NULL,
  PRIMARY KEY (`idUSER`, `idSKILL`),
  CONSTRAINT `fk_has_skill_user`
    FOREIGN KEY (`idUSER`)
    REFERENCES `STUDENT_ALUM` (`User_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_has_skill_skill`
    FOREIGN KEY (`idSKILL`)
    REFERENCES `SKILL` (`idSKILL`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
