-- Used for creating the database without breaking dependencies.
USE `job_beacon_maine`;
DROP TABLE IF EXISTS `SKILL_RESOURCE`;
DROP TABLE IF EXISTS `REQUIRES_SKILL`;
DROP TABLE IF EXISTS `HAS_SKILL`;
DROP TABLE IF EXISTS `SKILL`;
DROP TABLE IF EXISTS `RESOURCE`;
DROP TABLE IF EXISTS `EDUCATION`;
DROP TABLE IF EXISTS `HIGHER_EDUCATION_INSTUTITE`;
DROP TABLE IF EXISTS `Job_Application`;
DROP TABLE IF EXISTS `Jobs_Temp`;
DROP TABLE IF EXISTS `Jobs`;
DROP TABLE IF EXISTS `STUDENT_ALUM`;
DROP TABLE IF EXISTS `RECRUITER`;
DROP TABLE IF EXISTS `USER`;
DROP TABLE IF EXISTS `Employer`;
DROP TABLE IF EXISTS `Location_Lookup`;