-- Used to for creating the database without breaking dependencies.
USE `job_beacon_maine`;
DROP TABLE IF EXISTS `EDUCATION`;
DROP TABLE IF EXISTS `RESOURCE`;
DROP TABLE IF EXISTS `SKILL`;
DROP TABLE IF EXISTS `SKILL_RESOURCE`;
DROP TABLE IF EXISTS `HIGHER_EDUCATION_INSTUTITE`;
DROP TABLE IF EXISTS `USER`;