DROP TABLE IF EXISTS `EDUCATION`;
CREATE TABLE `job_beacon_maine`.`EDUCATION` (
  `idEDUCATION` INT NOT NULL,
  `DEGREE` ENUM('Bachelors','Masters','Associates','PHD') NOT NULL,
  `GRAD_DATE` datetime NOT NULL,
  `idUSER` INT NOT NULL,
  `idHIGHER_EDUCATION_INSTUTITE` INT NOT NULL,
  PRIMARY KEY (`idEDUCATION`),
  KEY `idUSER_idx` (`idUSER`),
  CONSTRAINT `idUSER` FOREIGN KEY (`idUSER`) REFERENCES `USER` (`idUSER`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `idHIGHER_EDUCATION_INSTUTITE` FOREIGN KEY (`idHIGHER_EDUCATION_INSTUTITE`) REFERENCES `HIGHER_EDUCATION_INSTUTITE` (`idHIGHER_EDUCATION_INSTUTITE`) ON DELETE CASCADE ON UPDATE CASCADE
);