DROP TABLE IF EXISTS `HAS_EDUCATION`;
CREATE TABLE `job_beacon_maine`.`HAS_EDUCATION` (
  `idUSER` INT NOT NULL,
  `idEDUCATION` INT NOT NULL,
  PRIMARY KEY (`idUSER`, `idEDUCATION`),
  INDEX `idEDUCATION_idx` (`idEDUCATION` ASC) VISIBLE,
  CONSTRAINT `idUSER`
    FOREIGN KEY (`idUSER`)
    REFERENCES `job_beacon_maine`.`EDUCATION` (`idUSER`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idEDUCATION`
    FOREIGN KEY (`idEDUCATION`)
    REFERENCES `job_beacon_maine`.`EDUCATION` (`idEDUCATION`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);