DROP TABLE IF EXISTS `HIGHER_EDUCATION_INSTUTITE`;
CREATE TABLE `job_beacon_maine`.`HIGHER_EDUCATION_INSTUTITE` (
  `idHIGHER_EDUCATION_INSTUTITE` INT NOT NULL,
  `NAME` VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (`idHIGHER_EDUCATION_INSTUTITE`)
)