DROP TABLE IF EXISTS `SKILL_RESOURCE`;
CREATE TABLE `job_beacon_maine`.`SKILL_RESOURCE` (
  `idRESOURCE` INT NOT NULL,
  `idSKILL` INT NOT NULL,
  PRIMARY KEY (`idRESOURCE`, `idSKILL`),
  INDEX `idSKILL_idx` (`idSKILL` ASC) VISIBLE,
  CONSTRAINT `idSKILL`
    FOREIGN KEY (`idSKILL`)
    REFERENCES `job_beacon_maine`.`SKILL` (`idSKILL`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idRESOURCE`
    FOREIGN KEY (`idRESOURCE`)
    REFERENCES `job_beacon_maine`.`RESOURCE` (`idRESOURCE`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);