DROP TABLE IF EXISTS `SKILL`;
CREATE TABLE `job_beacon_maine`.`SKILL` (
  `idSKILL` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (`idSKILL`),
  UNIQUE KEY `NAME_UNIQUE` (`NAME`)
);